import { Router, type IRouter } from "express";
import healthRouter from "./health";
import bookmarksRouter from "./bookmarks";
import notesRouter from "./notes";
import hardAyahsRouter from "./hardAyahs";
import memorizationRouter from "./memorization";
import lastReadRouter from "./lastRead";
import goalsRouter from "./goals";
import streaksRouter from "./streaks";
import tasbihRouter from "./tasbih";
import dashboardRouter from "./dashboard";
import searchRouter from "./search";
import moodsRouter from "./moods";
import khatmRouter from "./khatm";
import libraryRouter from "./library";
import donationsRouter from "./donations";
import readingLogsRouter from "./readingLogs";
import pinnedVersesRouter from "./pinnedVerses";
import collectionsRouter from "./collections";
import devRouter from "./dev";
import verseOfDayRouter from "./verseOfDay";
import profileRouter from "./profile";
import supportRouter from "./support";
import authRouter from "./auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/bookmarks", bookmarksRouter);
router.use("/notes", notesRouter);
router.use("/hard-ayahs", hardAyahsRouter);
router.use("/memorization", memorizationRouter);
router.use("/last-read", lastReadRouter);
router.use("/goals", goalsRouter);
router.use("/streaks", streaksRouter);
router.use("/tasbih", tasbihRouter);
router.use("/dashboard", dashboardRouter);
router.use("/search", searchRouter);
router.use("/moods", moodsRouter);
router.use("/khatm", khatmRouter);
router.use("/library", libraryRouter);
router.use("/donations", donationsRouter);
router.use("/reading-logs", readingLogsRouter);
router.use("/pinned-verses", pinnedVersesRouter);
router.use("/collections", collectionsRouter);
router.use("/dev", devRouter);
router.use("/verse-of-day", verseOfDayRouter);
router.use("/profile", profileRouter);
router.use("/support", supportRouter);
router.use("/auth", authRouter);

export default router;
